modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved."

[[mods]]
modId="sereneseasonsplus"
version="${mod_version}"
displayName="Serene Seasons Plus"
description="Addon to Serene Seasons."
authors="Gabou"
logoFile = "logo.png"
credits=""
updateJSONURL=""

[[dependencies."sereneseasonsplus"]]
modId = "betterdays"
mandatory = true
versionRange = "*"
side = "BOTH"

[[dependencies."sereneseasonsplus"]]
modId = "sereneseasons"
mandatory = true
versionRange = "*"
side = "BOTH"

[[dependencies."sereneseasonsplus"]]
modId = "projectatmosphere"
mandatory = false
versionRange = "[0.9.0.0,)"
side = "BOTH"
