modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="sereneseasonsextended"
version="1.0.6"
displayName="Serene Seasons Extended"
description="Addon to Serene Seasons."
authors="Gabou"
credits=""
updateJSONURL=""

[[dependencies."sereneseasonsextended"]]
modId = "betterdays"
mandatory = true
versionRange = "*"
side = "BOTH"

[[dependencies."sereneseasonsextended"]]
modId = "sereneseasons"
mandatory = true
versionRange = "*"
side = "BOTH"

[[dependencies."sereneseasonsextended"]]
modId = "projectatmosphere"
mandatory = false
versionRange = "*"
side = "BOTH"
